name: Dev Branch

on:
  push:
    branches:
      - dev  # Workflow triggers on pushes to the main branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --output ${{ runner.workspace }}/osu!progress

    - name: Test
      run: dotnet test

    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ${{ runner.workspace }}/osu!progress
